const BYPASS_REMEDIATION = "bypass";
const CAPTCHA_REMEDIATION = "captcha";
const BAN_REMEDIATION = "ban";
const ORDERED_REMEDIATIONS = [
  BYPASS_REMEDIATION,
  CAPTCHA_REMEDIATION,
  BAN_REMEDIATION,
];

module.exports = {
  BYPASS_REMEDIATION,
  CAPTCHA_REMEDIATION,
  BAN_REMEDIATION,
  ORDERED_REMEDIATIONS,
};
